name: Run industrySector

permissions:
  contents: write

on:
  schedule:
    - cron: '0 16 * * *'  # 8:00 AM PT
    - cron: '0 19 * * *'  # 11:00 AM PT
    - cron: '0 1 * * *'   # 5:00 PM PT (next day UTC)
    - cron: '0 5 * * *'   # 9:00 PM PT (next day UTC)
    - cron: '0 */12 * * *'  # Every 2 hours
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run industrySector.py script
        run: python industrySector.py

      - name: Commit and Push Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sector_trends1.csv sector_trends3.csv industry_trends3.csv industry_trends1.csv sector_trends5.csv sector_trendsSP500.csv industry_trendsSP500.csv
          git commit -m "Run industry Sector"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
