name: Run Stokks Youtube Script Daily

on:
  schedule:
    - cron: '0 16 * * *'  # 8:00 AM PT
    - cron: '0 5 * * *'   # 9:00 PM PT (next day UTC)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up OpenAI API Key
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run Stokks script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python stokks.py

      - name: Commit and Push CSV and Text Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git stash --include-untracked  # Stash all changes
          git fetch origin
          git pull --rebase origin main
          git stash pop || echo "No stash to apply"
          git add output.csv sorted_dictionary_output.txt StockList.txt recommendations_output.txt
          git commit -m "Latest to be latest youtube stokks" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
