name: Run Stokks at all

on:
  schedule:
    - cron: '0 20 * * *'  # 12:00 PM PT (UTC is 8 hours ahead of PT during standard time)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run proxy.py script
        run: python proxy.py

      - name: Commit and Push Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add outputnew.csv OldData.txt
          git commit -m "Run Stokks Script Daily"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
