name: Run yahoo gainers

on:
  schedule:
    - cron: '0 16 * * *'  # 8:00 AM PT
    - cron: '0 19 * * *'  # 11:00 AM PT
    - cron: '0 1 * * *'   # 5:00 PM PT (next day UTC)
    - cron: '0 5 * * *'   # 9:00 PM PT (next day UTC)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run yahoo.py script
        run: python yahoo.py

      - name: Commit and Push Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add YahooDirec.txt yahoo.csv
          git commit -m "Run yahoo gainers"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
